{{- if not (lookup "rbac.authorization.k8s.io/v1beta1" "ClusterRole" "" .Values.ingressController.clusterRole.name) }}
{{- if .Values.ingressController.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name:  {{ .Values.ingressController.clusterRole.name }}
  annotations:
    "helm.sh/resource-policy": keep
rules:
  - apiGroups:
      - "configuration.konghq.com"
    resources:
      - kongclusterplugins
    verbs:
      - get
      - list
      - watch
{{- end -}}
{{- end }}
